d={}

name=input("Enter the friends name:")
lang=input("Enter langage name:")
d.update({name: lang})
name=input("Enter the friends name:")
lang=input("Enter langage name:")
d.update({name: lang})
name=input("Enter the friends name:")
lang=input("Enter langage name:")
d.update({name: lang})
name=input("Enter the friends name:")
lang=input("Enter langage name:")
d.update({name: lang})
print(d)