marks=[]
f1=int(input("enter the marks: ") )
marks.append(f1)
f2=int(input("enter the marks: ") )
marks.append(f2)
f3=int(input("enter the marks: ") )
marks.append(f3)
f4=int(input("enter the marks: ") )
marks.append(f4)
f5=int(input("enter the marks: ") )
marks.append(f5)
f6=int(input("enter the marks: ") )
marks.append(f6)
f8=int(input("enter the marks: ") )
marks.append(f8)
f8=int(input("enter the marks: ") )
marks.append(f8)
marks.sort()
print(marks)